services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:stable
    container_name: local_n8n_orchestrator
    user: "root"
    restart: unless-stopped
    network_mode: "host"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - NODES_EXCLUDE="[]"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      # Mounts your workspace database directly into your repository folder for tracking safety
      - /home/dsama/HardDrive/Repositories/hybrid_mesh_ai/control_plane/n8n_local_data:/home/node/.n8n
      - /home/dsama/HardDrive/Repositories/hybrid_mesh_ai/vault:/data/storage
      - /home/dsama/HardDrive/Repositories/hybrid_mesh_ai/vault/documentation:/files
